# -*- coding: utf-8 -*-
DATA = {
"kicker": "PRACTICAL GUIDE",
"cover_lines": ["CLAUDE", "COWORK"],
"cover_sub": "How to set up Claude so it actually does the work for you, instead of handing back polished text that misses the point.",
"foot_l": ["Based on material by Ruben Hassid", "and Anthropic documentation"],
"foot_r": ["A4 FORMAT · 18 PAGES.", "READS IN ONE COFFEE."],
"toc": [
    ("01","What Cowork is and how it differs from Chat"),
    ("02","Five key capabilities"),
    ("03","Forget prompts. Think in files"),
    ("04","How to set it up in 30 minutes"),
    ("05","Context file strategy"),
    ("06","AskUserQuestion: let Claude ask you"),
    ("07","One prompt for everything"),
    ("08","Plugins: instant specialization"),
    ("09","Connectors: Claude inside your tools"),
    ("10","Real use cases"),
    ("11","Where Cowork still struggles"),
    ("12","Checklist: your first 30 minutes"),
],
"sections": [
{"num":"01","header":"COWORK VS CHAT","title":"Less chatbot, more coworker","blocks":[
  ("para","Most people think Claude works like ChatGPT: a text box, you type, it answers. That's claude.ai, the browser version. Cowork works differently."),
  ("para","Cowork lives right on your computer. It reads and writes files in real folders, builds Word documents, creates spreadsheets with working formulas, and installs plugins for your profession. And when it's missing data, it asks, instead of guessing and handing back pretty garbage."),
  ("para","Essentially it's the power of Claude Code (the agentic tool for developers), reworked for everyone else. No terminal, no command line, no code. Just describe the result, show it your files, and get on with your day while it works."),
  ("callout","Rule of thumb","Need a quick answer or a brainstorm, go to Chat. Need a result as a file (analysis, spreadsheet, presentation, report), go to Cowork. If the output should be a document, that's Cowork."),
  ("subhead","Three modes of Claude for different jobs"),
  ("table",["","CHAT","COWORK","PROJECTS"],[
    ["What it is","Text box: you type, it answers","Agent on your computer: reads files, makes documents","Workspace with memory and files"],
    ["Access","Web, desktop, mobile","Desktop only","Web, desktop, mobile"],
    ["Files","Via download","Straight into your folder","Via download"],
    ["Plugins","No","Yes, slash commands","No"],
    ["Connectors","Yes","Yes","Yes"],
    ["Memory","None between sessions","Through files and instructions","Yes, within the project"],
  ],[0.17,0.27,0.32,0.24]),
  ("para","Same Claude, three ways to work with it. Only Cowork touches your files directly."),
]},
{"num":"02","header":"FIVE CAPABILITIES","title":"Five things this was all built for","blocks":[
  ("para","Cowork differs from a regular chat not in its interface, but in what it can do with its hands. Here are the five pillars."),
  ("deflist",[
    ("2.1","File access","Claude reads and writes files in a folder on your computer. No more exported, dragged, waited, downloaded, put it back. You pick a folder, it works with it directly. That's the difference between a tool you visit and a colleague who sits inside your environment."),
    ("2.2","Clarifying questions","Any other AI guesses when the task is vague: it picks an interpretation, gets going, and hands back a polished answer to the wrong question. Cowork stops and builds a form with options and buttons. You answer in a couple of minutes and get an exact result."),
    ("2.3","Plugins","Without a plugin Cowork is a brilliant generalist, but without your industry vocabulary. Plugins fix that: one click, and it speaks the language of marketing, finance, or law."),
    ("2.4","Instructions","Cowork has no memory between sessions, every conversation starts from a blank slate. Instructions solve that: you write standing directions once, and they load at the start of every session. Global ones apply everywhere, folder ones kick in when you pick a specific folder."),
    ("2.5","Connectors","Link Claude to Slack, Google Drive, Notion, Figma, Asana, and fifty-odd other services. Once connected, it reads messages, digs into files, checks your calendar. Connectors are free on every plan."),
  ]),
  ("label","Anthropic released 11 official plugins in January 2026"),
  ("table",["PLUGIN","WHAT IT'S FOR"],[
    ["Productivity","Tasks, calendars, daily workflows"],
    ["Marketing","Content, campaigns, brand voice"],
    ["Sales","Account research, call prep"],
    ["Finance","Modeling, analysis, reporting"],
    ["Data Analysis","SQL, dashboards, data exploration"],
    ["Legal","Contract review, legal research"],
    ["Product Mgmt","Specs, roadmaps, user stories"],
    ["Customer Support","Ticket handling, reply drafts"],
  ],[0.32,0.68]),
  ("para","Plugins are exactly what wiped $285B off legal software stocks: Thomson Reuters dropped 16% in a single session."),
]},
{"num":"03","header":"THINK IN FILES","title":"Forget prompts","blocks":[
  ("para","ChatGPT trained you to write better, longer prompts. In Cowork the game is different: it's built on text files."),
  ("para","Take everything you know about your work: your writing style, your company rules, your best examples, past experience. Put it into text files, drop them in a folder, and show it to Claude. It's like an SOP for an employee. Only here the employee is Claude, and its SOP is your Claude Cowork folder."),
  ("callout","Key idea","The more quality context you give through files, the less you need to prompt. The result shifts from typical AI to it really sounds like something I would write myself. ChatGPT taught you to write better prompts, a skill that keeps depreciating. Cowork teaches you to give better context, and that compounds."),
]},
{"num":"04","header":"30-MINUTE SETUP","title":"Setup in 30 minutes","blocks":[
  ("para","Open your calendar and block half an hour. Then go step by step."),
  ("deflist",[
    ("00–05 MIN","Install","Download the desktop app from claude.com/download (macOS or Windows). You need a paid plan: Pro at $20/mo or Max from $100. Open the app, switch to the Cowork tab at the top, and pick Opus 4.6 with Extended thinking, the smartest model."),
    ("05–10 MIN","Context files","Create a Claude Cowork folder with four subfolders inside: ABOUT ME (1–2 files about you and your style), TEMPLATES (strong past work), PROJECTS (current projects with briefs), CLAUDE OUTPUTS (where finished results land)."),
    ("10–15 MIN","Global instructions","Settings → Cowork → Edit next to Global Instructions. Write the essentials: name and role, tone preferences, default formats, working style, and what to avoid."),
    ("15–20 MIN","First task","Pick a folder and start a session: read all the files in this folder, then help me with a task, ask clarifying questions first. Choose something you already do well, so you can instantly tell whether the result is right."),
    ("20–25 MIN","Plugin","Customize in the sidebar → Browse plugins. Good starting points: Productivity, Marketing, Sales. Type a slash in the chat to see the slash commands."),
    ("25–30 MIN","Connector","Settings → Connectors. Connect the tool you use most: Slack, Google Drive, or Notion. Authorize it and ask Claude something about it. That is the moment it all clicks."),
  ]),
]},
{"num":"05","header":"FILE STRATEGY","title":"One good file beats 50 uploads","blocks":[
  ("para","Stop thinking about better prompts and start thinking about better files. Three of them handle almost everything."),
  ("deflist",[
    ("","about-me.md","Who you are and what you do. Three things: how you make money, how you like to communicate, and a piece of writing you are proud of."),
    ("","brand-voice.md","How you sound. Your phrases, what reads as off to you, examples of strong texts, and the AI-writing patterns to avoid."),
    ("","working-style.md","How you want Claude to work. Whether to ask questions first, short or long answers, which file formats you prefer."),
  ]),
  ("callout","Tip from Ruben Hassid","Files work by compounding. Each week you refine them a little, and Claude gets better specifically at your work. Save them as .md, the format Claude reads best."),
]},
{"num":"06","header":"ASKUSERQUESTION","title":"Let Claude ask you","blocks":[
  ("para","This is the feature that changes how you work, and almost no guide explains it properly."),
  ("para","Always add one simple thing to the end of your prompt:"),
  ("prompt","Don't start yet. First ask me clarifying questions so we define the approach together. Only begin once we've agreed."),
  ("para","Cowork will build an interactive form with clickable options. You answer in a couple of minutes and get an exact result instead of fighting a text box."),
  ("callout","Mindset shift","With a context window over a million tokens, you don't have to fear hallucinations on complex projects. Once Claude has read your files and pinned down the task with questions, the result stands firmly on real data."),
]},
{"num":"07","header":"ONE PROMPT","title":"One prompt that kicks off everything","blocks":[
  ("para","About 80% of Cowork sessions can start the same way. Here's the skeleton."),
  ("prompt","I want to [TASK] so that [SUCCESS CRITERION]. First study my CLAUDE COWORK folder. Then ask questions via AskUserQuestion. I want to refine the approach with you before you start."),
  ("para","Claude reads the context files and builds a form with questions about audience, goals, and preferences. You click through in a minute, it shows a plan, you approve, it executes and creates real files in the folder. If something goes sideways midway, you interrupt, it rebuilds the form and picks up where it left off."),
  ("callout","Mac tip","System Settings → Keyboard → Text Replacement. Add a shortcut (for example /prompt) and paste this template into it. Now typing /prompt drops it in automatically."),
]},
{"num":"08","header":"PLUGINS","title":"Plugins: specialization in one click","blocks":[
  ("para","Customize → Browse plugins (or claude.com/plugins) → Install. Then type a slash in the chat and watch the slash commands appear."),
  ("prompt","/marketing:draft-content Write a LinkedIn post about [topic]. Use the tone from brand-voice.md. Audience: [audience].","Marketing"),
  ("prompt","/data:explore There's a CSV file in this folder. Summarize what's in it, flag anomalies, and suggest three analyses worth running.","Data analysis"),
  ("prompt","Review the NDA in this folder. Flag anything unusual or one-sided.","Legal"),
  ("para","Each plugin can be tuned to your company: Claude asks questions and remembers the answers."),
]},
{"num":"09","header":"CONNECTORS","title":"Claude inside your tools","blocks":[
  ("para","Settings → Connectors. A catalog of 50+ integrations. Add, authorize, done. Set up once, and access is there in every session."),
  ("callout","Free everywhere","Connectors are available on every plan, including the free one. Connecting tools costs nothing, you only pay for Claude's actual work."),
  ("prompt","Summarize the key decisions from the #project-alpha Slack channel over the last two weeks.\nFind my Slack messages from the past 7 days and gather everything that needs a reply.\nPull the Q1 numbers from the revenue file in Google Drive.","Examples"),
]},
{"num":"10","header":"REAL USE CASES","title":"What it looks like in real work","blocks":[
  ("para","Four scenarios where Cowork saves hours. The context folder is already set up."),
  ("subhead","Content writing"),
  ("para","The folder holds about-me.md, an anti-AI-cliché guide, and a couple of strong past texts."),
  ("prompt","I want to write my next newsletter about [topic]. First study the CLAUDE COWORK folder, then ask questions via AskUserQuestion. I want to refine the approach before you start."),
  ("para","Claude reads every file, asks about audience, tone, length, and angle, and builds an outline. You edit, it writes, and thanks to the voice profile the text actually sounds like you."),
  ("subhead","Consulting document"),
  ("prompt","A client sent a brief for a 2026 AI adoption strategy, it's in /projects/client-x/. Read the brief, my deliverable template, and past examples. Make a first draft in .docx. Ask questions first."),
  ("para","It checks the brief against your template, sometimes asks about things you hadn't considered, and drops a finished .docx right into the folder."),
  ("subhead","Financial model"),
  ("prompt","I want a spreadsheet modeling a potential exit from my social accounts. Start with AskUserQuestion to pin down the current numbers. Then build a spreadsheet in the style of Wall Street financial models."),
  ("para","Claude asks clarifying questions, builds an Excel with formulas, and finds and fixes its own mistakes while you're busy with something else."),
  ("subhead","Automatic Monday briefing"),
  ("para","A special case: Cowork works without you. Set up a /weekly-briefings/ folder and use /schedule."),
  ("prompt","Every Monday at 7am, research [competitors] for news, product updates, and pricing changes. Save a summary to /weekly-briefings/ in markdown. Only events from the last 7 days."),
  ("para","As long as the computer is on and the app is open, it runs on its own. You wake up and the briefing is ready."),
]},
{"num":"11","header":"LIMITATIONS","title":"Where Cowork still struggles","blocks":[
  ("para","An honest look at the limits, so you know what to expect. This is a research preview, and it can make mistakes."),
  ("deflist",[
    ("","No memory between sessions","Every new session starts blank. Fixed with context .md files and global instructions."),
    ("","Burns through limits fast","Reading files and building documents eats noticeably more than a regular chat. On Pro, keep an eye on Settings → Usage during heavy use."),
    ("","Desktop only","No mobile version or sync. Keep your context files in a cloud folder (iCloud, Dropbox)."),
    ("","Stops when you close it","Close the app and the task halts. Don't close the window while it's working."),
    ("","Doesn't make images","For photos and illustrations, use other services."),
    ("","Agents sometimes miss","Cowork breaks a complex task into parts. About 10% of the time one agent goes off track, so check what it creates and don't send anything to a client unread."),
  ]),
]},
{"num":"12","header":"CHECKLIST","title":"Your first 30 minutes","blocks":[
  ("checklist",[
    "Download the desktop app from claude.com/download",
    "Get Pro ($20/mo) or Max ($100/mo)",
    "Open Cowork (the tab up top between Chat and Code)",
    "Pick Opus 4.6 + Extended thinking",
    "Create a Claude Cowork folder with ABOUT ME, TEMPLATES, PROJECTS, CLAUDE OUTPUTS subfolders",
    "Write about-me.md: who you are, what you do, a sample of your work",
    "Write brand-voice.md: how you sound, examples, anti-patterns",
    "Write working-style.md: your format preferences",
    "Set up Global Instructions (Settings → Cowork)",
    "Run your first task with clarifying questions",
    "Install one plugin (Productivity is a good start)",
    "Connect one connector (Slack or Google Drive)",
  ]),
  ("callout","The value curve starts immediately","Setup takes about half an hour. But the payoff isn't someday later, it shows up with the very first task you used to do by hand."),
]},
],
"closing": ["STOP", "PROMPTING.", "START GIVING", "CONTEXT."],
"close_attrib": ["Based on material by Ruben Hassid (How to AI)", "and Anthropic documentation · 2026"],
"links": ["CLAUDE.COM/DOWNLOAD", "CLAUDE.COM/PLUGINS"],
}
